Repository uption/uption, pull requests merged in 2020-04, with the labels that each got.

#27 Add ping timeout and get only ping latency
  src/collectors/http.rs
  src/collectors/ping.rs
  src/config.rs
  src/message.rs
  src/uption.rs
  uption.toml
Labels: feature

#33 Implement exporter retry logic
  Cargo.lock
  Cargo.toml
  src/exporters/mod.rs
  src/uption.rs
Labels: feature

#38 Improve exporter error handling
  src/exporters/influxdb.rs
  src/exporters/mod.rs
  src/exporters/stdout.rs
Labels: feature

#40 Fix ping parsing failure
  src/collectors/ping.rs
Labels: bug

#47 Add getters to Message and make attributes private
  src/exporters/influxdb.rs
  src/exporters/mod.rs
  src/message.rs
Labels: refactor

#53 Implement Configure trait and refactor
  src/collectors/mod.rs
  src/config.rs
  src/exporters/mod.rs
  src/uption.rs
Labels: refactor

#56 Replace http_req crate with reqwest
  Cargo.lock
  Cargo.toml
  src/collectors/http.rs
  src/collectors/ping.rs
  src/error.rs
  src/exporters/influxdb.rs
  src/message.rs
  src/url/url.rs
Labels: feature, refactor

#59 Fix block autosquash commits runs on master branch
  .github/workflows/ci.yml
Labels: bug

#48 Implement logging
  Cargo.lock
  Cargo.toml
  src/collectors/mod.rs
  src/config.rs
  src/exporters/mod.rs
  src/logging.rs
  src/main.rs
  src/uption.rs
  uption.toml
Labels: feature

#61 Fix libc version too new in release builds
  .github/workflows/create-release.yml
  Cargo.lock
  Cargo.toml
Labels: bug
